### ISSUE TITLE
Error type too wide

### ISSUE THREAD

**Issue by rgrempel** [simonh1000/file-reader#1]
I think the error type in your signature is a little too wide.

By saying:

```
getTextFile : String -> Task error String
```

... you are basically saying that the error type of the `Task` can be anything. (Since 'error' is just a label ... it will match any type).

But, your native code actually does return errors of a specific type ... that is

```
Task.fail({ctor : 'read_fail'})
Task.fail({ctor : 'no_file_specified'})
```

And, you haven't actually defined that error type in Elm terms.

I think you need something like this in the Elm file:

```
type Error
    = ReadFail
    | NoFileSpecified
```

and then the signature would be (note the capital "E")

```
getTextFile : String -> Task Error String
```

and then in the native code it would be something like:

```
Task.fail({ctor : 'ReadFail'})
Task.fail({ctor : 'NoFileSpecified'})
```

But, I'm just doing that off the top of my head -- I might not have that quite right, but I hope that's the general idea.

**Comment by simonh1000** [comment]
Thanks - that makes sense and I've implemented it. (This my very first 'code review'.)

**Comment by rgrempel** [comment]
That looks better. The other thing that would probably be a good idea is an example that demonstrated that this works. (Well, a test would be even better, but I can see that this would not be trivial to write a typical test for.) Ideally, the example would also allow a user to "exercise" the error conditions, though I suppose "ReadFail" would be a little hard to simulate.

I should say that I'm merely an officious bystander, not an actual "code reviewer" -- so take whatever I say with a grain of salt :-)

**Comment by simonh1000** [comment]
Thanks in any event - your comments made complete sense
