### ISSUE TITLE
Publishing order for Libraries

### ISSUE THREAD

**Issue by danyx23** [simonh1000/file-reader#16]
Ok, I pulled MimeType into its own library: http://package.elm-lang.org/packages/danyx23/elm-mimetype/1.0.0/ . I also pulled out DragDrop and renamed it to DropZone: https://github.com/danyx23/elm-dropzone . But now we have a bit of an awkward dependency chain. Mimetype is standalone and is fine, but the examples in FileReader need DropZone to work but the DropZone implementation depends on FileReader (which makes it impossible to publish this package before FileReader has passed native review if I understand the process correctly).

I see two possible solutions: 
1. Extract the stuff DropZone needs (parseDroppedFiles and NativeFile) into a seperate library so that DropZone only has a dependy on this lib, not on FileReader. So the dependency chain could be MimeType -> FileReader for the main project and MimeType -> ParseAndNativeFileLibrary -> DropZone -> FileReader for the examples
2. Publish FileReader as it is with it's own copy of DropZone (maybe still named DragDrop) with a note that it will be replaced soon. Wait for native review, then publish DropZone and update FileReader.

What do you think? (BTW the filereader library looks very nice now!)

**Comment by simonh1000** [comment]
On the library, thanks - you may have seen that Jeff Smits provided a beautiful solution to the Files decoder

I will refactor to use Mimetype as a library this evening.

On the main question, I see the issue. I think 2 is the way forward, while 1 raises a question for you. At present DropZone focuses on drag 'n drop to read files, but there are lots of other uses for drag 'n drop on a webpage, and perhaps you should be generalising for that, which would probably lead you to remove the FileReader dependency (as it is too specific an action to take `ondrop`)

**Comment by danyx23** [comment]
:100:! Thank you, that was a much needed prod into the right direction :). I just rewrote DropZone to get the Json.decoder as a parameter, that gets rid of the dependency. I think this should allow me to publish dropzone as is and if you like you can use the new library for the examples (or I could rewrite them to use the library if you like, just let me know!). 

It's true, I will want to extend the library to handle other DnD operations too, but I think even specializes like this it might be useful for some other people, so I think publishing an initial version is justified.
