### ISSUE TITLE
Support for large files

### ISSUE THREAD

**Issue by ghost** [simonh1000/file-reader#17]
Trying to use this API with a text file about 30MB in size, but the entire application crashes. I started the `readAsTextFile` task and it never came back after that.

**Comment by chowevtfy** [comment]
It works fine, actually. It's something weird about the browser causing things to crash with really large strings. I just forked this repo to base64 encode it first, and that fixed the problem. Strangely enough, that should make the data even longer.

**Comment by simonh1000** [comment]
Thanks for the comments. I have seen other implementations of this sort of library in other languages send buffers, and that may be better for larger files.
However, that would require more native code (see http://stackoverflow.com/questions/7431365/filereader-readasbinarystring-to-upload-files) and I will hold off of that until 0.17 is out

**Comment by simonh1000** [comment]
Looks like you solved your own issue, so I will close this
