### ISSUE TITLE
Consider case where id is not found

### ISSUE THREAD

**Issue by rgrempel** [simonh1000/file-reader#2]
I was looking at this snippet:

``` js
            var fileUpload = document.getElementById(id).files[0];
            if (fileUpload)
                reader.readAsText(fileUpload);
            else callback(Task.fail({ctor : 'NoFileSpecified'}));
```

... and I was wondering whether it might throw an error if the supplied `id` is not found on the page. For instance, if I do:

``` js
document.getElementById("bob").files[0]
```

.. and there is nothing with an `id` of "bob", then a TypeError is thrown.

Come to think of it, you'd have a similar problem if the `id` was found, but had no `files` property -- that would throw an error as well, when you try to use it as an array.

Of course, you've handled the case where there is a `files` property but there is no `files[0]`.

So, it might be a good idea to add a few more error conditions -- i.e. something like `IdNotFound` and checking whether `files` is null before using it as an array.

**Comment by simonh1000** [comment]
Thanks Ryan, I've made amendments along the lines you suggested. Let me know what you think

**Comment by rgrempel** [comment]
That looks good to me.
