### ISSUE TITLE
0.18 migration

### ISSUE THREAD

**Issue by chancyk** [simonh1000/file-reader#20]
I use a version of your FileReader for my project which I had to migrate for 0.18, but I haven't tested against all the endpoints as I only use `readAsTextFile`. The only things I had to change though were:

```
Json.objectN -> Json.mapN
Basics.fst   -> Tuple.first
Basics.snd   -> Tuple.second
x (:=) y     -> field x y
```

And the MimeTypes dependency seemed to need no changes. Here's a link to the full [migration guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md).

**Comment by simonh1000** [comment]
Thanks. I'm always in two minds about what to do with this library given that it relies on native code, and thus can't be published. Would love to hear about your use case(s)

**Comment by simonh1000** [comment]
https://github.com/simonh1000/file-reader/commit/42499b836da0f57de1b8555069d14a8cca8cffe9
