### ISSUE TITLE
Document installation process

### ISSUE THREAD

**Issue by Birowsky** [simonh1000/file-reader#22]
i used elm-github-install for the package, I manually imported the `Native/FileReader.js` to my `main.js`

but now i get this error:
```
FileReader.js:4Uncaught ReferenceError: _elm_lang$core$Native_Scheduler is not defined
    at FileReader.js:4

```
could you please precisely document the installation process?

**Comment by simonh1000** [comment]
Note in particular that you need to add "native-modules": true, to your elm-package.json file as is done in the examples.

**Comment by Birowsky** [comment]
I found my mistakes:

- I was importing the native js inside my project by hand
- elm-hot-loader doesn't work nicely with native modules (maybe i have old version)

Thanx a ton for the package!

**Comment by simonh1000** [comment]
I run native code with this hot leading 

https://github.com/simonh1000/elm-hot-loading-starter
