### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by SergKam** [simonh1000/file-reader#26]
Thank you for the library.
I just have some concerns. 
First, it would be nice to check whether reader[method] exists at all
https://github.com/simonh1000/file-reader/blob/master/src/Native/FileReader.js#L31

Second, Theoretically, since you are creating a closure here inside a callback, a reference to fileObjectToRead may still be kept after the callback's execution aka memory leak. Correct me if I'm wrong but:
```
const result = reader[method](fileObjectToRead); 
fileObjectToRead = null; 
return result;
```
may guarantee the release of the reference.1
If the callback is intended to be called many times then, of course, I'm wrong.

**Comment by simonh1000** [comment]
Let me know whether you think fixes the important issues you raise

**Comment by SergKam** [comment]
@simonh1000 Yes, this is just perfect! Thank you for your contribution!
