### ISSUE TITLE
compilation error - letting too much stuff through

### ISSUE THREAD

**Issue by matteosister** [simonh1000/file-reader#29]
I'm trying to use version 1.4.0 of this library with elm 0.18.0 and I get this error:

```
ERROR in ____
Module build failed: Error: Compiler process exited with error Compilation failed
Problem in dependency simonh1000/file-reader 1.4.0

The elm-package.json constraints of 'simonh1000/file-reader' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.

In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.
```

any ideas?

**Comment by matteosister** [comment]
Just to let you know: by incrementing the minimum requirement in the elm-lang/core dependency to the actual core version everything works. 

So I think you should just tag a new release with the new dependency version:

```
"elm-lang/core": "5.1.1 <= v < 6.0.0"
```

**Comment by simonh1000** [comment]
thanks - let me look into that

**Comment by simonh1000** [comment]
Can you let me know what exactly you did to get an error as I'm not seeing it when I use the examples

**Comment by matteosister** [comment]
I think it depends on the version you got in your project elm-pagkage.json, I have: 

```
"elm-lang/core": "5.1.1 <= v < 6.0.0",
```

with this, and by adding the dependency:
```
"simonh1000/file-reader": "1.0.0 <= v < 2.0.0"
```

I get the error.

The solution was **updating the file-reader elm-package.json** dependency from:
```
"elm-lang/core": "5.0.0 <= v < 6.0.0"
```

to:
```
"elm-lang/core": "5.1.1 <= v < 6.0.0"
```

maybe another solution could be changing the requirement of my project to match the one that you define in file-reader....but it sounds strange. 

My guess is that elm says: project A requires `"elm-lang/core": "5.1.1 <= v < 6.0.0"`, project B (which is required by A) requires `"elm-lang/core": "5.0.0 <= v < 6.0.0"` and so it complains that project B is too **open**...

**Comment by matteosister** [comment]
maybe you just need a new release that supports elm-lang/core version 5.1.*

**Comment by matteosister** [comment]
after the 1.5.* release, everything seems to work fine...without any changes to the code. Could be a problem with elm runtime itself....

**Comment by simonh1000** [comment]
Great great news I was racking my brains for how changing the config file
could have any real impact in practice
