### ISSUE TITLE
Support elm 0.19

### ISSUE THREAD

**Issue by Munksgaard** [simonh1000/file-reader#34]
Any plans for adding Elm 0.19 support?

**Comment by simonh1000** [comment]
Hi, I would be interested in knowing what you would want form 0.19 support?

The point is that it is no longer possible at all to provide the sort of native/kernel code that I did before, as that has now been completely banned. As a result the obvious solution is via ports, but it is also not possible to publish port code to the Elm package management system.

So one alternative is to publish the elm code as a 'library' but there is not much there really. Another is that I write a blog about using ports to read files. And there may be others.  I would welcome views.

**Comment by Munksgaard** [comment]
I guess you're probably right. I've put together my own functionality for 0.19 with inspiration from your module, but it would probably be nice for others if there was an easy-to-copy solution. 

I know that there are some elm libraries that do allow javascript code, but I think perhaps they have to be part of elm-explorations or something. For instance, the [markdown](https://github.com/elm-explorations/markdown) module for elm 0.19 is just a shallow wrapper over some javascript code. I don't know if elm-explorations is meant for others than @evancz.

**Comment by simonh1000** [comment]
I did offer to update my code to be published in elm-explorations but the offer was rejected!

**Comment by Munksgaard** [comment]
Alright. I'll see if I can find time to write up a little guide on how to use your approach in 0.19. Thanks for your work!
