### ISSUE TITLE
DragDrop should not render anything

### ISSUE THREAD

**Issue by danyx23** [simonh1000/file-reader#6]
I've thought a bit about the implementation of DragDrop in the library. I think your refactoring of moving the two Attributes out of the component and provide it at init from the parent is really nice. But do we need a visual representation of the Dropzone at all?

My thinking is inspired by the ideas in the [React Drag n Drop](http://gaearon.github.io/react-dnd/) library by Dan Abramov. What he did there was provide a very nice declarative interface for React Components that wanted to support Drag and Drop. I don't know how familiar you are with React, but there is this concept of "Higher Order Components" that are basically functions that wrap the creation of a component and have internal state and pass some results down to the nested, user-supplied components. The nested components use the props from the HOC but all the rendering is up to them.

Anyhow, I am thinking that we should maybe just provide a helper to add the required event handlers to the thing the user wants to use as a dropzone but leave implementing a view for it to the user. This would mean that the only state we would manage for now in the DragDrop Model would be the HoverState. Everything else would be up to the user.

This may sound like less convenience, but I think that something as simple as displaying an image inside the dropzone that changes when the user hovers would be a very common idea. It could be done right now of course but then half of the internal model is redundant. I think it would be better if we try to make the API as minimal as possible.

What are your thoughts?

**Comment by simonh1000** [comment]
Basically I agree.
I would love to remove all the state, as as many actions as possible, from whatever ends up in the 'library'. And while attaching the drag events to a `div` is about as general as it gets, it is still ultimately arbitrary.

Perhaps react can dispose of all state because it can use `:hover` events in CSS, whereas that is harder for Elm.

Want to create a file that parallels `DragDrop.elm`?

**Comment by danyx23** [comment]
It's cool that we are on the same page with this :). 

By parallels do you mean another file that tries to be a minimal version of what DragDrop.elm does ATM? If so yes, I'll give it a shot.

**Comment by simonh1000** [comment]
Yes, DragDrop.elm may perhaps end up in examples folder as - with its state - it is not library material, but it's pretty useful stuff so let's try your react-inspired approach in a new file

**Comment by danyx23** [comment]
:+1:

**Comment by simonh1000** [comment]
Are you planning to move DragDrop to a separate library? If so, we need you to publish that so that we can update the examples to use the library
