### ISSUE TITLE
Extract DragDrop and MimeTypes into two very small standalone libraries?

### ISSUE THREAD

**Issue by danyx23** [simonh1000/file-reader#9]
I am starting to think that the DragDrop and MimeType should maybe become two mini packages. I think you hinted at some point that they don't really belong in the FileReader library. So we could put them into the examples directory, but maybe it's more useful to make two small libs out of them. Since they don't have any native code it should be pretty painless to publish them. 

I am also getting more and more convinced that the mimeType field in the NativeFile type should not be a Maybe. The MimeType type already has an option for unkown mime types and I don't think this field is allowed to be missing according to the HTML 5 File Api draft.

What do you think?

**Comment by simonh1000** [comment]
Agreed, and this needs to happen before publishing the FileReader library

**Comment by danyx23** [comment]
Hi Simon, perfect, I'll try to publish it tomorrow. Thanks for access to the repo, I think I'll leave most decisions to you but feel free to delegate tasks :)
